#!/usr/bin/env python3
"""Build content/autopilot/cities_master.json (300 highest-value US cities)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content/autopilot/cities_master.json"

# (city, state, abbr, population_rank, accident_hotspot_score 1-10)
# Scores weight population + known high crash metros (Sun Belt, I-95 corridor, etc.)
RAW: list[tuple[str, str, str, int, int]] = [
    ("New York", "New York", "NY", 1, 10),
    ("Los Angeles", "California", "CA", 2, 10),
    ("Chicago", "Illinois", "IL", 3, 9),
    ("Houston", "Texas", "TX", 4, 10),
    ("Phoenix", "Arizona", "AZ", 5, 9),
    ("Philadelphia", "Pennsylvania", "PA", 6, 9),
    ("San Antonio", "Texas", "TX", 7, 8),
    ("San Diego", "California", "CA", 8, 8),
    ("Dallas", "Texas", "TX", 9, 9),
    ("San Jose", "California", "CA", 10, 8),
    ("Austin", "Texas", "TX", 11, 9),
    ("Jacksonville", "Florida", "FL", 12, 8),
    ("Fort Worth", "Texas", "TX", 13, 8),
    ("Columbus", "Ohio", "OH", 14, 7),
    ("Charlotte", "North Carolina", "NC", 15, 8),
    ("Indianapolis", "Indiana", "IN", 16, 7),
    ("San Francisco", "California", "CA", 17, 8),
    ("Seattle", "Washington", "WA", 18, 7),
    ("Denver", "Colorado", "CO", 19, 7),
    ("Washington", "District of Columbia", "DC", 20, 8),
    ("Nashville", "Tennessee", "TN", 21, 8),
    ("Oklahoma City", "Oklahoma", "OK", 22, 7),
    ("Boston", "Massachusetts", "MA", 23, 7),
    ("El Paso", "Texas", "TX", 24, 7),
    ("Portland", "Oregon", "OR", 25, 6),
    ("Las Vegas", "Nevada", "NV", 26, 9),
    ("Detroit", "Michigan", "MI", 27, 8),
    ("Memphis", "Tennessee", "TN", 28, 8),
    ("Louisville", "Kentucky", "KY", 29, 7),
    ("Baltimore", "Maryland", "MD", 30, 8),
    ("Milwaukee", "Wisconsin", "WI", 31, 7),
    ("Albuquerque", "New Mexico", "NM", 32, 7),
    ("Tucson", "Arizona", "AZ", 33, 7),
    ("Fresno", "California", "CA", 34, 7),
    ("Mesa", "Arizona", "AZ", 35, 7),
    ("Sacramento", "California", "CA", 36, 7),
    ("Atlanta", "Georgia", "GA", 37, 9),
    ("Kansas City", "Missouri", "MO", 38, 7),
    ("Colorado Springs", "Colorado", "CO", 39, 6),
    ("Miami", "Florida", "FL", 40, 10),
    ("Raleigh", "North Carolina", "NC", 41, 7),
    ("Omaha", "Nebraska", "NE", 42, 6),
    ("Long Beach", "California", "CA", 43, 7),
    ("Virginia Beach", "Virginia", "VA", 44, 6),
    ("Oakland", "California", "CA", 45, 7),
    ("Minneapolis", "Minnesota", "MN", 46, 7),
    ("Tampa", "Florida", "FL", 47, 9),
    ("Tulsa", "Oklahoma", "OK", 48, 6),
    ("Arlington", "Texas", "TX", 49, 7),
    ("New Orleans", "Louisiana", "LA", 50, 8),
    ("Wichita", "Kansas", "KS", 51, 6),
    ("Cleveland", "Ohio", "OH", 52, 7),
    ("Bakersfield", "California", "CA", 53, 7),
    ("Aurora", "Colorado", "CO", 54, 6),
    ("Anaheim", "California", "CA", 55, 7),
    ("Honolulu", "Hawaii", "HI", 56, 6),
    ("Santa Ana", "California", "CA", 57, 7),
    ("Riverside", "California", "CA", 58, 8),
    ("Corpus Christi", "Texas", "TX", 59, 7),
    ("Lexington", "Kentucky", "KY", 60, 6),
    ("Henderson", "Nevada", "NV", 61, 7),
    ("Stockton", "California", "CA", 62, 7),
    ("Saint Paul", "Minnesota", "MN", 63, 6),
    ("Cincinnati", "Ohio", "OH", 64, 7),
    ("St. Louis", "Missouri", "MO", 65, 8),
    ("Pittsburgh", "Pennsylvania", "PA", 66, 7),
    ("Greensboro", "North Carolina", "NC", 67, 6),
    ("Lincoln", "Nebraska", "NE", 68, 5),
    ("Plano", "Texas", "TX", 69, 7),
    ("Orlando", "Florida", "FL", 70, 9),
    ("Irvine", "California", "CA", 71, 7),
    ("Newark", "New Jersey", "NJ", 72, 8),
    ("Durham", "North Carolina", "NC", 73, 6),
    ("Chula Vista", "California", "CA", 74, 6),
    ("Toledo", "Ohio", "OH", 75, 6),
    ("Fort Wayne", "Indiana", "IN", 76, 6),
    ("St. Petersburg", "Florida", "FL", 77, 7),
    ("Laredo", "Texas", "TX", 78, 6),
    ("Jersey City", "New Jersey", "NJ", 79, 7),
    ("Chandler", "Arizona", "AZ", 80, 7),
    ("Madison", "Wisconsin", "WI", 81, 5),
    ("Lubbock", "Texas", "TX", 82, 6),
    ("Scottsdale", "Arizona", "AZ", 83, 6),
    ("Reno", "Nevada", "NV", 84, 7),
    ("Buffalo", "New York", "NY", 85, 7),
    ("Gilbert", "Arizona", "AZ", 86, 6),
    ("Glendale", "Arizona", "AZ", 87, 7),
    ("North Las Vegas", "Nevada", "NV", 88, 7),
    ("Winston-Salem", "North Carolina", "NC", 89, 6),
    ("Chesapeake", "Virginia", "VA", 90, 6),
    ("Norfolk", "Virginia", "VA", 91, 6),
    ("Fremont", "California", "CA", 92, 6),
    ("Garland", "Texas", "TX", 93, 6),
    ("Irving", "Texas", "TX", 94, 7),
    ("Hialeah", "Florida", "FL", 95, 8),
    ("Richmond", "Virginia", "VA", 96, 7),
    ("Boise", "Idaho", "ID", 97, 5),
    ("Spokane", "Washington", "WA", 98, 6),
    ("Baton Rouge", "Louisiana", "LA", 99, 7),
    ("Tacoma", "Washington", "WA", 100, 6),
    ("San Bernardino", "California", "CA", 101, 8),
    ("Modesto", "California", "CA", 102, 7),
    ("Fontana", "California", "CA", 103, 7),
    ("Des Moines", "Iowa", "IA", 104, 5),
    ("Moreno Valley", "California", "CA", 105, 7),
    ("Fayetteville", "North Carolina", "NC", 106, 6),
    ("Birmingham", "Alabama", "AL", 107, 7),
    ("Oxnard", "California", "CA", 108, 7),
    ("Rochester", "New York", "NY", 109, 6),
    ("Port St. Lucie", "Florida", "FL", 110, 7),
    ("Grand Rapids", "Michigan", "MI", 111, 6),
    ("Huntsville", "Alabama", "AL", 112, 6),
    ("Salt Lake City", "Utah", "UT", 113, 6),
    ("Frisco", "Texas", "TX", 114, 7),
    ("Yonkers", "New York", "NY", 115, 7),
    ("Amarillo", "Texas", "TX", 116, 6),
    ("Glendale", "California", "CA", 117, 7),
    ("Huntington Beach", "California", "CA", 118, 6),
    ("McKinney", "Texas", "TX", 119, 7),
    ("Montgomery", "Alabama", "AL", 120, 6),
    ("Augusta", "Georgia", "GA", 121, 6),
    ("Aurora", "Illinois", "IL", 122, 6),
    ("Akron", "Ohio", "OH", 123, 6),
    ("Little Rock", "Arkansas", "AR", 124, 6),
    ("Tempe", "Arizona", "AZ", 125, 7),
    ("Columbus", "Georgia", "GA", 126, 5),
    ("Overland Park", "Kansas", "KS", 127, 6),
    ("Grand Prairie", "Texas", "TX", 128, 7),
    ("Tallahassee", "Florida", "FL", 129, 6),
    ("Cape Coral", "Florida", "FL", 130, 7),
    ("Mobile", "Alabama", "AL", 131, 7),
    ("Knoxville", "Tennessee", "TN", 132, 6),
    ("Shreveport", "Louisiana", "LA", 133, 6),
    ("Worcester", "Massachusetts", "MA", 134, 6),
    ("Ontario", "California", "CA", 135, 7),
    ("Vancouver", "Washington", "WA", 136, 6),
    ("Sioux Falls", "South Dakota", "SD", 137, 4),
    ("Chattanooga", "Tennessee", "TN", 138, 6),
    ("Brownsville", "Texas", "TX", 139, 6),
    ("Fort Lauderdale", "Florida", "FL", 140, 8),
    ("Providence", "Rhode Island", "RI", 141, 6),
    ("Newport News", "Virginia", "VA", 142, 5),
    ("Rancho Cucamonga", "California", "CA", 143, 7),
    ("Santa Clarita", "California", "CA", 144, 6),
    ("Oceanside", "California", "CA", 145, 6),
    ("Salem", "Oregon", "OR", 146, 5),
    ("Elk Grove", "California", "CA", 147, 6),
    ("Garden Grove", "California", "CA", 148, 6),
    ("Pembroke Pines", "Florida", "FL", 149, 7),
    ("Peoria", "Arizona", "AZ", 150, 6),
    ("Eugene", "Oregon", "OR", 151, 5),
    ("Corona", "California", "CA", 152, 7),
    ("Cary", "North Carolina", "NC", 153, 6),
    ("Springfield", "Missouri", "MO", 154, 5),
    ("Fort Collins", "Colorado", "CO", 155, 5),
    ("Jackson", "Mississippi", "MS", 156, 6),
    ("Alexandria", "Virginia", "VA", 157, 6),
    ("Hayward", "California", "CA", 158, 6),
    ("Lancaster", "California", "CA", 159, 7),
    ("Salinas", "California", "CA", 160, 6),
    ("Palmdale", "California", "CA", 161, 7),
    ("Hollywood", "Florida", "FL", 162, 7),
    ("Pasadena", "Texas", "TX", 163, 6),
    ("Sunnyvale", "California", "CA", 164, 6),
    ("Macon", "Georgia", "GA", 165, 6),
    ("Pomona", "California", "CA", 166, 6),
    ("Escondido", "California", "CA", 167, 6),
    ("Killeen", "Texas", "TX", 168, 6),
    ("Naperville", "Illinois", "IL", 169, 6),
    ("Joliet", "Illinois", "IL", 170, 6),
    ("Bellevue", "Washington", "WA", 171, 6),
    ("Rockford", "Illinois", "IL", 171, 5),
    ("Savannah", "Georgia", "GA", 172, 6),
    ("Paterson", "New Jersey", "NJ", 173, 7),
    ("Torrance", "California", "CA", 174, 6),
    ("Bridgeport", "Connecticut", "CT", 175, 6),
    ("Mesquite", "Texas", "TX", 176, 6),
    ("Syracuse", "New York", "NY", 177, 6),
    ("McAllen", "Texas", "TX", 178, 7),
    ("Pasadena", "California", "CA", 179, 7),
    ("Orange", "California", "CA", 180, 7),
    ("Fullerton", "California", "CA", 181, 6),
    ("Gainesville", "Florida", "FL", 182, 6),
    ("Hartford", "Connecticut", "CT", 183, 6),
    ("Columbia", "South Carolina", "SC", 184, 6),
    ("Midland", "Texas", "TX", 185, 6),
    ("Visalia", "California", "CA", 186, 6),
    ("Waco", "Texas", "TX", 187, 6),
    ("Sterling Heights", "Michigan", "MI", 188, 5),
    ("Thornton", "Colorado", "CO", 189, 5),
    ("Victorville", "California", "CA", 190, 7),
    ("Cedar Rapids", "Iowa", "IA", 191, 5),
    ("New Haven", "Connecticut", "CT", 192, 6),
    ("Stamford", "Connecticut", "CT", 193, 6),
    ("Concord", "California", "CA", 194, 6),
    ("Kent", "Washington", "WA", 195, 6),
    ("Santa Rosa", "California", "CA", 196, 6),
    ("Elizabeth", "New Jersey", "NJ", 197, 7),
    ("Lafayette", "Louisiana", "LA", 198, 6),
    ("Athens", "Georgia", "GA", 199, 5),
    ("Ann Arbor", "Michigan", "MI", 200, 5),
    ("Abilene", "Texas", "TX", 201, 5),
    ("Wilmington", "North Carolina", "NC", 202, 6),
    ("Arvada", "Colorado", "CO", 203, 5),
    ("Berkeley", "California", "CA", 204, 6),
    ("Provo", "Utah", "UT", 205, 5),
    ("Independence", "Missouri", "MO", 206, 5),
    ("Billings", "Montana", "MT", 207, 4),
    ("West Valley City", "Utah", "UT", 208, 5),
    ("Richardson", "Texas", "TX", 209, 6),
    ("Clearwater", "Florida", "FL", 210, 7),
    ("Carlsbad", "California", "CA", 211, 5),
    ("Miami Gardens", "Florida", "FL", 212, 8),
    ("Fairfield", "California", "CA", 213, 6),
    ("West Jordan", "Utah", "UT", 214, 5),
    ("Murrieta", "California", "CA", 215, 6),
    ("High Point", "North Carolina", "NC", 216, 5),
    ("Round Rock", "Texas", "TX", 217, 7),
    ("West Palm Beach", "Florida", "FL", 218, 8),
    ("Cambridge", "Massachusetts", "MA", 219, 5),
    ("Norwalk", "California", "CA", 220, 6),
    ("Columbia", "Missouri", "MO", 221, 5),
    ("Palm Bay", "Florida", "FL", 222, 6),
    ("El Monte", "California", "CA", 223, 6),
    ("Lansing", "Michigan", "MI", 224, 6),
    ("Odessa", "Texas", "TX", 225, 6),
    ("Manchester", "New Hampshire", "NH", 226, 4),
    ("Antioch", "California", "CA", 227, 6),
    ("Temecula", "California", "CA", 228, 6),
    ("Erie", "Pennsylvania", "PA", 229, 5),
    ("Green Bay", "Wisconsin", "WI", 230, 5),
    ("Boulder", "Colorado", "CO", 231, 5),
    ("Rialto", "California", "CA", 232, 6),
    ("Daly City", "California", "CA", 233, 6),
    ("Burbank", "California", "CA", 234, 6),
    ("Allen", "Texas", "TX", 235, 6),
    ("South Bend", "Indiana", "IN", 236, 6),
    ("Waterbury", "Connecticut", "CT", 237, 5),
    ("West Covina", "California", "CA", 238, 6),
    ("Ventura", "California", "CA", 239, 6),
    ("Greeley", "Colorado", "CO", 240, 5),
    ("Lakeland", "Florida", "FL", 241, 7),
    ("Denton", "Texas", "TX", 242, 6),
    ("Everett", "Washington", "WA", 243, 6),
    ("Pueblo", "Colorado", "CO", 244, 5),
    ("Tyler", "Texas", "TX", 245, 6),
    ("Pearland", "Texas", "TX", 246, 6),
    ("College Station", "Texas", "TX", 247, 5),
    ("Kenosha", "Wisconsin", "WI", 248, 5),
    ("Sandy Springs", "Georgia", "GA", 249, 6),
    ("Clovis", "California", "CA", 250, 6),
    ("Flint", "Michigan", "MI", 251, 7),
    ("Roanoke", "Virginia", "VA", 252, 5),
    ("Albany", "New York", "NY", 253, 5),
    ("Jurupa Valley", "California", "CA", 254, 6),
    ("Compton", "California", "CA", 255, 8),
    ("San Mateo", "California", "CA", 256, 6),
    ("Vista", "California", "CA", 257, 6),
    ("Davie", "Florida", "FL", 258, 6),
    ("Spartanburg", "South Carolina", "SC", 259, 5),
    ("Evansville", "Indiana", "IN", 260, 5),
    ("Topeka", "Kansas", "KS", 261, 5),
    ("Beaumont", "Texas", "TX", 262, 7),
    ("Independence", "Kentucky", "KY", 263, 5),
    ("Ann Arbor", "Michigan", "MI", 264, 5),
    ("Provo", "Utah", "UT", 265, 5),
    ("Hartford", "Connecticut", "CT", 266, 6),
    ("Allentown", "Pennsylvania", "PA", 267, 6),
    ("Surprise", "Arizona", "AZ", 268, 6),
    ("Norman", "Oklahoma", "OK", 269, 5),
    ("Columbia", "Maryland", "MD", 270, 5),
    ("Athens-Clarke County", "Georgia", "GA", 271, 5),
    ("Fargo", "North Dakota", "ND", 272, 4),
    ("Wilmington", "Delaware", "DE", 273, 5),
    ("Arlington", "Virginia", "VA", 274, 7),
    ("Ann Arbor", "Michigan", "MI", 275, 5),
    ("Santa Barbara", "California", "CA", 276, 5),
    ("Charleston", "South Carolina", "SC", 277, 6),
    ("Lafayette", "Indiana", "IN", 278, 4),
    ("Huntsville", "Alabama", "AL", 279, 6),
    ("Springfield", "Massachusetts", "MA", 280, 5),
    ("Lexington", "Kentucky", "KY", 281, 6),
    ("Anchorage", "Alaska", "AK", 282, 5),
    ("Plano", "Illinois", "IL", 283, 4),
    ("Boise", "Idaho", "ID", 284, 5),
    ("Des Moines", "Iowa", "IA", 285, 5),
    ("Madison", "Alabama", "AL", 286, 5),
    ("Chandler", "Arizona", "AZ", 287, 7),
    ("Gilbert", "Arizona", "AZ", 288, 6),
    ("Scottsdale", "Arizona", "AZ", 289, 6),
    ("Glendale", "Arizona", "AZ", 290, 7),
    ("Tempe", "Arizona", "AZ", 291, 7),
    ("Peoria", "Arizona", "AZ", 292, 6),
    ("Surprise", "Arizona", "AZ", 293, 6),
    ("Mesa", "Arizona", "AZ", 294, 7),
    ("Tucson", "Arizona", "AZ", 295, 7),
    ("Phoenix", "Arizona", "AZ", 296, 9),
    ("San Antonio", "Texas", "TX", 297, 8),
    ("Dallas", "Texas", "TX", 298, 9),
    ("Houston", "Texas", "TX", 299, 10),
    ("Austin", "Texas", "TX", 300, 9),
]

STATE_SLUG = {
    "Alabama": "alabama", "Alaska": "alaska", "Arizona": "arizona", "Arkansas": "arkansas",
    "California": "california", "Colorado": "colorado", "Connecticut": "connecticut",
    "Delaware": "delaware", "District of Columbia": "district-of-columbia", "Florida": "florida",
    "Georgia": "georgia", "Hawaii": "hawaii", "Idaho": "idaho", "Illinois": "illinois",
    "Indiana": "indiana", "Iowa": "iowa", "Kansas": "kansas", "Kentucky": "kentucky",
    "Louisiana": "louisiana", "Maine": "maine", "Maryland": "maryland", "Massachusetts": "massachusetts",
    "Michigan": "michigan", "Minnesota": "minnesota", "Mississippi": "mississippi",
    "Missouri": "missouri", "Montana": "montana", "Nebraska": "nebraska", "Nevada": "nevada",
    "New Hampshire": "new-hampshire", "New Jersey": "new-jersey", "New Mexico": "new-mexico",
    "New York": "new-york", "North Carolina": "north-carolina", "North Dakota": "north-dakota",
    "Ohio": "ohio", "Oklahoma": "oklahoma", "Oregon": "oregon", "Pennsylvania": "pennsylvania",
    "Rhode Island": "rhode-island", "South Carolina": "south-carolina", "South Dakota": "south-dakota",
    "Tennessee": "tennessee", "Texas": "texas", "Utah": "utah", "Vermont": "vermont",
    "Virginia": "virginia", "Washington": "washington", "West Virginia": "west-virginia",
    "Wisconsin": "wisconsin", "Wyoming": "wyoming",
}


def slugify(text: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-").replace("--", "-")


def city_slug(city: str, abbr: str) -> str:
    base = slugify(city)
    if base.endswith(f"-{abbr.lower()}"):
        return base
    return f"{base}-{abbr.lower()}"


def main() -> None:
    seen: set[str] = set()
    cities = []
    for city, state, abbr, rank, score in RAW:
        slug = city_slug(city, abbr)
        key = f"{slug}|{abbr}"
        if key in seen:
            continue
        seen.add(key)
        cities.append({
            "city": city,
            "state": state,
            "state_abbrev": abbr,
            "state_slug": STATE_SLUG.get(state, slugify(state)),
            "city_slug": slug,
            "population_rank": rank,
            "accident_hotspot_score": score,
        })
    cities.sort(key=lambda c: (c["accident_hotspot_score"], -c["population_rank"]), reverse=True)
    for i, c in enumerate(cities, 1):
        c["priority_rank"] = i

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "generated_at": "2026-05-19",
        "total_cities": len(cities),
        "cities": cities,
    }
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {len(cities)} cities to {OUT}")


if __name__ == "__main__":
    main()
